### ISSUE TITLE
Possible issue with JSON schema draft-04

### ISSUE THREAD

**Issue by dollarrama** [alexandrainst/node-red-contrib-json-multi-schema#8]
I tried to validate an OCPP 1.6 schema with the Validator node. [https://www.openchargealliance.org/downloads/](https://www.openchargealliance.org/downloads/)
It works fine with the examples you provided by referencing fiware.github.io.

In this example I just changed the msg.schemaUrl to an OCPP 1.6 schema on my local machine.
The schema looks like this:
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "urn:OCPP:1.6:2019:12:AuthorizeRequest",
    "title": "AuthorizeRequest",
    "type": "object",
    "properties": {
        "idTag": {
            "type": "string",
            "maxLength": 20
        }
    },
    "additionalProperties": false,
    "required": [
        "idTag"
    ]
}
```
When I trigger the function node to pipe forward the msg.payload and the msg.schemaUrl (set to OCPP schema) to the Validator node, my Raspberry pi (running Ubuntu) crashes nearly completely. WebUI is not reachable anymore also SSH does not work - only reboot changes the situation.

Could it be that "draft-04" is not supported by the validator?
At least I identified that tag "id" is "$id" in newer JSON versions ...

To reproduce:
Use above schema as msg.schemaUrl and pipe it with any payload to the JSON schema validator.

If you need more information, please let me know.
Thanks

P.S: All components are up to date with latest release versions.

**Comment by Alkarex** [comment]
Long delay here, but the Ajv, the underlying library, supports multiple JSON schema versions: https://ajv.js.org/json-schema.html#json-schema-versions
However, different versions cannot be combined, and I have been hesitating in adding a user-defined option and/or some automated way to guess the version

**Comment by Alkarex** [comment]
I have added support for different versions of JSON Schema in release 1.6.0: https://github.com/alexandrainst/node-red-contrib-json-multi-schema/releases/tag/v1.6.0
